#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "arm-linux-androideabi-gcc -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -mandroid -I/include -B/lib -O3 -fomit-frame-pointer -Wall"
  #define PLATFORM "android"
  #define DATE ""
#endif
